# NumPy Exercises

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks, and then you'll be asked some more complicated questions.

#### Import NumPy as np

In [1]:
import numpy as np

#### Create an array of 10 zeros

In [2]:
# arr = np.array([0, 0, 0, 0, 0, 0, 0, 0, 0])
arr0 = np.zeros(10)
print(arr0)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### Create an array of 10 ones

In [3]:
print(np.ones(10))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


#### Create an array of 10 fives

In [4]:
print(np.full(10, 5))

[5 5 5 5 5 5 5 5 5 5]


#### Create an array of the integers from 10 to 50

In [5]:
print(np.arange(10,51))

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


#### Create an array of all the even integers from 10 to 50

In [6]:
print(np.arange(10,51,2))

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


#### Create a 3x3 matrix with values ranging from 0 to 8

In [7]:
arr2 = np.arange(0,9)
print(arr2.reshape(3,3))

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### Create a 3x3 identity matrix

In [8]:
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### Use NumPy to generate a random number between 0 and 1

In [9]:
print(np.random.rand())

0.7772186006938347


#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [19]:
arr3 = np.random.normal(loc=0, scale=1, size=25)
print(arr3)
print(f"The mean is :{np.mean(arr3)}")
print(f"The std. is :{np.std(arr3)}")

[-0.63865821  1.49751911  1.09060603 -0.92411308  1.4256014  -0.54606837
 -1.23779673 -1.23458503  0.99827703  0.7369311   1.94238644  0.61779536
  0.65492071  0.05021433  0.83601066  0.86105144  0.09199752 -0.32318262
 -0.23055332 -0.16081117  0.95189361 -2.93659885 -1.66430965  0.83552892
 -0.36367946]
The mean is :0.093215086048793
The std. is :1.1090782382810702


#### Create the following matrix:

In [11]:
a = np.array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1])
b = np.array([[0.1], [0.2], [0.3], [0.4], [0.5], [0.6], [0.7], [0.8], [0.9], [1]])
print(a*b)

[[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 ]
 [0.02 0.04 0.06 0.08 0.1  0.12 0.14 0.16 0.18 0.2 ]
 [0.03 0.06 0.09 0.12 0.15 0.18 0.21 0.24 0.27 0.3 ]
 [0.04 0.08 0.12 0.16 0.2  0.24 0.28 0.32 0.36 0.4 ]
 [0.05 0.1  0.15 0.2  0.25 0.3  0.35 0.4  0.45 0.5 ]
 [0.06 0.12 0.18 0.24 0.3  0.36 0.42 0.48 0.54 0.6 ]
 [0.07 0.14 0.21 0.28 0.35 0.42 0.49 0.56 0.63 0.7 ]
 [0.08 0.16 0.24 0.32 0.4  0.48 0.56 0.64 0.72 0.8 ]
 [0.09 0.18 0.27 0.36 0.45 0.54 0.63 0.72 0.81 0.9 ]
 [0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  0.9  1.  ]]


#### Create an array of 20 linearly spaced points between 0 and 1:

In [12]:
print(np.linspace(0,1,20))

[0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]


## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [13]:
print(np.arange(1,26).reshape(5,5))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [14]:
#Using broadcasting
arrA = np.arange(12,23,5)
# print(arrA)
final = arrA[:,None] + np.arange(0,4) #(3,1) + (,4)
print(final)

[[12 13 14 15]
 [17 18 19 20]
 [22 23 24 25]]


In [15]:
print(np.array(20))

20


In [16]:
print(np.arange(2,13,5).reshape(3,1))

[[ 2]
 [ 7]
 [12]]


In [17]:
print(np.arange(21,26,1))

[21 22 23 24 25]


In [18]:
print(np.arange(16,26,1).reshape(2,5))

[[16 17 18 19 20]
 [21 22 23 24 25]]


# Great Job!